# Generated by Django 4.0.3 on 2022-03-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
    ]
