# Generated by Django 4.0.3 on 2022-03-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_country_id_alter_country_country_code'),
    ]

    operations = [
    ]
