# Generated by Django 4.0.3 on 2022-03-23 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_country_id_alter_country_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.country', to_field='country_code', verbose_name='کشور'),
        ),
    ]
