# Generated by Django 4.0.3 on 2022-03-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_report_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='persons_fully_vaccinated',
            field=models.IntegerField(default=0, verbose_name='تعداد واکسینه کامل'),
        ),
        migrations.AddField(
            model_name='report',
            name='persons_fully_vaccinated_per100',
            field=models.FloatField(default=0, verbose_name='درصد واکسینه کامل'),
        ),
        migrations.AddField(
            model_name='report',
            name='total_vaccinations',
            field=models.IntegerField(default=0, verbose_name='تعداد کل واکسینه'),
        ),
        migrations.AddField(
            model_name='report',
            name='total_vaccinations_per100',
            field=models.FloatField(default=0, verbose_name='درصد کل واکسینه'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cumulative_cases',
            field=models.IntegerField(default=0, verbose_name='ابتلا تجمعی'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cumulative_deaths',
            field=models.IntegerField(default=0, verbose_name='مرگ و میر تجمعی'),
        ),
        migrations.AlterField(
            model_name='report',
            name='new_cases',
            field=models.IntegerField(default=0, verbose_name='ابتلا جدید'),
        ),
        migrations.AlterField(
            model_name='report',
            name='new_deaths',
            field=models.IntegerField(default=0, verbose_name='مرگ و میر جدید'),
        ),
    ]
